# Generated by Django 4.1 on 2023-03-01 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_about', models.CharField(max_length=200, verbose_name='titulo')),
                ('texto_about', models.TextField(max_length=500, verbose_name='texto')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'about',
                'verbose_name_plural': 'abouts',
                'ordering': ['titulo_about'],
            },
        ),
    ]
