# Generated by Django 4.1 on 2023-03-01 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='texto_about',
            field=models.TextField(max_length=2000, verbose_name='texto'),
        ),
    ]
