# Generated by Django 4.1 on 2023-03-05 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_about_texto_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='texto_about_dos',
            field=models.TextField(default=12, max_length=2000, verbose_name='texto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='titulo_about_dos',
            field=models.CharField(default=12, max_length=200, verbose_name='titulo'),
            preserve_default=False,
        ),
    ]
