# Generated by Django 4.1 on 2023-03-05 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_about_texto_about_dos_about_titulo_about_dos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='texto_about_dos',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='texto dos'),
        ),
        migrations.AlterField(
            model_name='about',
            name='titulo_about_dos',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='titulo dos'),
        ),
    ]
