# Generated by Django 4.1 on 2023-03-05 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_about_texto_about_dos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_skill', models.CharField(max_length=200, verbose_name='titulo')),
                ('nombre_skill', models.TextField(max_length=2000, verbose_name='texto')),
                ('imagen_skill', models.ImageField(blank=True, null=True, upload_to='imagen_skill')),
                ('porcentaje_skill', models.IntegerField(verbose_name='duree')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'skill',
                'verbose_name_plural': 'skills',
                'ordering': ['nombre_skill'],
            },
        ),
    ]
