# Generated by Django 4.1 on 2023-03-05 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='nombre_skill',
            field=models.TextField(max_length=2000, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='porcentaje_skill',
            field=models.IntegerField(verbose_name='%'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='tipo_skill',
            field=models.CharField(max_length=200, verbose_name='tipo'),
        ),
    ]
