# Generated by Django 4.1 on 2023-03-08 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_skill_nombre_skill_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_project', models.CharField(max_length=200, verbose_name='nombre')),
                ('tipo_project', models.CharField(max_length=200, verbose_name='tipo')),
                ('desc_project', models.TextField(max_length=2000, verbose_name='descripcion')),
                ('imagen_project', models.ImageField(blank=True, null=True, upload_to='imagen_skill')),
                ('link_project', models.CharField(max_length=200, null=True, verbose_name='link')),
                ('desc_project_one', models.IntegerField(null=True, verbose_name='description 1')),
                ('desc_project_one_imagen', models.ImageField(blank=True, null=True, upload_to='imagen_project')),
                ('desc_project_two', models.IntegerField(null=True, verbose_name='description 2')),
                ('desc_project_two_imagen', models.ImageField(blank=True, null=True, upload_to='imagen_project')),
                ('desc_project_three', models.IntegerField(null=True, verbose_name='description 3')),
                ('desc_project_three_imagen', models.ImageField(blank=True, null=True, upload_to='imagen_project')),
                ('desc_project_four', models.IntegerField(null=True, verbose_name='description 4')),
                ('desc_project_four_imagen', models.ImageField(blank=True, null=True, upload_to='imagen_project')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
                'ordering': ['name_project'],
            },
        ),
    ]
